name: Lightning Strike
author: MichaelM04
main: LightningStrike\Main
version: 2.0
api: 1.13.0
description: Lightning Strike Very Simple Just Strikes Lightning On Ground When A Player Dies,Joins,Quits
